[package]
name = "release_test"
version = "0.1.0"
authors = ["daniel.sanchez@iohk.io <sanchez.quiros.daniel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
